### ISSUE TITLE
Calling clientside methods in multiple locations on server

### ISSUE THREAD

**Issue by kristi71111** [alec016/modular-machinery-reborn#20]
Refer to https://github.com/alec016/modular-machinery-reborn/blob/c021d49d0b0c896ec45ea41a6e85fa2afc30093e/src/main/java/es/degrassi/mmreborn/common/block/BlockController.java#L149
https://github.com/alec016/modular-machinery-reborn/blob/c021d49d0b0c896ec45ea41a6e85fa2afc30093e/src/main/java/es/degrassi/mmreborn/common/block/BlockController.java#L109
https://github.com/alec016/modular-machinery-reborn/blob/c021d49d0b0c896ec45ea41a6e85fa2afc30093e/src/main/java/es/degrassi/mmreborn/common/block/BlockController.java#L117
This causes a lot of features to be un-usable on a dedicated server.

Example Stack: 

`java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/blockentity/BlockEntityRenderer for invalid dist DEDICATED_SERVER
	at TRANSFORMER/modular_machinery_reborn@1.1.16/es.degrassi.mmreborn.common.block.BlockController.playerWillDestroy(BlockController.java:117) ~[modular_machinery_reborn-1.21.1-1.1.16.jar%23707!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:261) ~[server-1.21.1-20240808.144430-srg.jar%23484!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:239) ~[server-1.21.1-20240808.144430-srg.jar%23484!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:157) ~[server-1.21.1-20240808.144430-srg.jar%23484!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1081)`

**Comment by alec016** [comment]
thanks for that, i didnt notice that was happening, i fix it for the next update
